// Validates the shared config model and generates the operator-managed client
// config. Server config generation is Worker-owned in src/worker/server-config.ts.
//
// Reference: https://github.com/rapiz1/rathole#configuration

import type { RatholeConfig, RatholeService } from "./types";

/** Quote a TOML string value, escaping backslashes and double quotes. */
function q(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** rathole service names must be usable as bare TOML keys. */
function isBareKey(name: string): boolean {
  return /^[A-Za-z0-9_-]+$/.test(name);
}

function serviceKey(name: string): string {
  return isBareKey(name) ? name : q(name);
}

export interface ValidationIssue {
  path: string;
  message: string;
}

const ADDR_RE = /^[^\s]+:\d{1,5}$/;

/** Validate a config, returning a list of human-readable problems (empty = ok). */
export function validateConfig(config: RatholeConfig): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  if (!config.bindAddr || !ADDR_RE.test(config.bindAddr)) {
    issues.push({
      path: "bindAddr",
      message: "Control channel bind address must look like host:port (e.g. 0.0.0.0:2333).",
    });
  }

  const seen = new Set<string>();
  config.services.forEach((svc, i) => {
    const base = `services[${i}]`;
    if (!svc.name.trim()) {
      issues.push({ path: `${base}.name`, message: "Service name is required." });
    } else if (seen.has(svc.name)) {
      issues.push({ path: `${base}.name`, message: `Duplicate service name "${svc.name}".` });
    }
    seen.add(svc.name);

    if (!svc.bindAddr || !ADDR_RE.test(svc.bindAddr)) {
      issues.push({
        path: `${base}.bindAddr`,
        message: `Service "${svc.name || i}" needs a valid public bind address (host:port).`,
      });
    }
  });

  const hasDefault = !!config.defaultToken?.trim();
  const missingTokens = config.services.filter((s) => !s.token?.trim());
  if (!hasDefault && missingTokens.length > 0) {
    issues.push({
      path: "defaultToken",
      message:
        "Set a default token, or give every service its own token. rathole requires a token for each service.",
    });
  }

  return issues;
}

/**
 * Generate a matching `client.toml`. This is a template the operator runs on the
 * machine behind NAT; `local_addr` defaults to the service's clientLocalAddr.
 */
export function generateClientToml(
  config: RatholeConfig,
  publicHost?: string,
): string {
  const remotePort = config.bindAddr.split(":").pop() ?? "2333";
  const host = publicHost?.trim() || "your-server-host";
  const out: string[] = [];
  out.push(`# rathole client config (run this on the machine behind NAT).`);
  out.push(`# Generated by rathole-manage.`);
  out.push("");
  out.push(`[client]`);
  out.push(`remote_addr = ${q(`${host}:${remotePort}`)}`);
  if (config.defaultToken?.trim()) out.push(`default_token = ${q(config.defaultToken)}`);
  out.push("");

  if (config.transport && config.transport !== "tcp") {
    out.push(`[client.transport]`);
    out.push(`type = ${q(config.transport)}`);
    if (config.transport === "noise" && config.noise?.pattern) {
      out.push(`[client.transport.noise]`);
      out.push(`pattern = ${q(config.noise.pattern)}`);
      if (config.noise.remotePublicKey)
        out.push(`remote_public_key = ${q(config.noise.remotePublicKey)}`);
    }
    if (config.transport === "websocket") {
      out.push(`[client.transport.websocket]`);
      out.push(`tls = ${config.websocket?.tls ? "true" : "false"}`);
    }
    out.push("");
  }

  for (const svc of config.services) {
    out.push(`[client.services.${serviceKey(svc.name)}]`);
    out.push(`type = ${q(svc.type)}`);
    out.push(`local_addr = ${q(svc.clientLocalAddr || localHint(svc))}`);
    if (svc.token?.trim()) out.push(`token = ${q(svc.token)}`);
    if (svc.nodelay !== undefined) out.push(`nodelay = ${svc.nodelay ? "true" : "false"}`);
    out.push("");
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function localHint(svc: RatholeService): string {
  // A sensible default local target based on the service name.
  const n = svc.name.toLowerCase();
  if (n.includes("ssh")) return "127.0.0.1:22";
  if (n.includes("web") || n.includes("http")) return "127.0.0.1:80";
  if (n.includes("rdp")) return "127.0.0.1:3389";
  return "127.0.0.1:8080";
}

export function defaultConfig(): RatholeConfig {
  return {
    bindAddr: "0.0.0.0:2333",
    defaultToken: "",
    transport: "tcp",
    services: [],
  };
}
