// Generates rathole-compatible TOML from the typed config model.
// Pure, dependency-free so it runs identically in the Worker and the browser.
//
// Reference: https://github.com/rapiz1/rathole#configuration

import type {
  GeneratedConfigs,
  Instance,
  RatholeConfig,
  RatholeService,
} from "./types";

/** Quote a TOML string value, escaping backslashes and double quotes. */
function q(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** rathole service names must be usable as bare TOML keys. */
function isBareKey(name: string): boolean {
  return /^[A-Za-z0-9_-]+$/.test(name);
}

function serviceKey(name: string): string {
  return isBareKey(name) ? name : q(name);
}

export interface ValidationIssue {
  path: string;
  message: string;
}

const ADDR_RE = /^[^\s]+:\d{1,5}$/;

/** Validate a config, returning a list of human-readable problems (empty = ok). */
export function validateConfig(config: RatholeConfig): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  if (!config.bindAddr || !ADDR_RE.test(config.bindAddr)) {
    issues.push({
      path: "bindAddr",
      message: "Control channel bind address must look like host:port (e.g. 0.0.0.0:2333).",
    });
  }

  const seen = new Set<string>();
  config.services.forEach((svc, i) => {
    const base = `services[${i}]`;
    if (!svc.name.trim()) {
      issues.push({ path: `${base}.name`, message: "Service name is required." });
    } else if (seen.has(svc.name)) {
      issues.push({ path: `${base}.name`, message: `Duplicate service name "${svc.name}".` });
    }
    seen.add(svc.name);

    if (!svc.bindAddr || !ADDR_RE.test(svc.bindAddr)) {
      issues.push({
        path: `${base}.bindAddr`,
        message: `Service "${svc.name || i}" needs a valid public bind address (host:port).`,
      });
    }
  });

  const hasDefault = !!config.defaultToken?.trim();
  const missingTokens = config.services.filter((s) => !s.token?.trim());
  if (!hasDefault && missingTokens.length > 0) {
    issues.push({
      path: "defaultToken",
      message:
        "Set a default token, or give every service its own token. rathole requires a token for each service.",
    });
  }

  return issues;
}

function transportBlock(config: RatholeConfig): string {
  const lines: string[] = [];
  lines.push(`[server.transport]`);
  lines.push(`type = ${q(config.transport)}`);

  if (config.transport === "tls" && config.tls) {
    lines.push(`[server.transport.tls]`);
    if (config.tls.pkcsPath) lines.push(`pkcs12 = ${q(config.tls.pkcsPath)}`);
    if (config.tls.keystorePassword)
      lines.push(`pkcs12_password = ${q(config.tls.keystorePassword)}`);
  }
  if (config.transport === "noise" && config.noise) {
    lines.push(`[server.transport.noise]`);
    if (config.noise.pattern) lines.push(`pattern = ${q(config.noise.pattern)}`);
    if (config.noise.localPrivateKey)
      lines.push(`local_private_key = ${q(config.noise.localPrivateKey)}`);
    if (config.noise.remotePublicKey)
      lines.push(`remote_public_key = ${q(config.noise.remotePublicKey)}`);
  }
  if (config.transport === "websocket" && config.websocket) {
    lines.push(`[server.transport.websocket]`);
    lines.push(`tls = ${config.websocket.tls ? "true" : "false"}`);
  }
  return lines.join("\n");
}

/** Generate the rathole `server.toml` for an instance's config. */
export function generateServerToml(config: RatholeConfig, instanceName?: string): string {
  const out: string[] = [];
  if (instanceName) out.push(`# rathole server config for "${instanceName}"`);
  out.push(`# Generated by rathole-manage — edit in the panel, not by hand.`);
  out.push("");
  out.push(`[server]`);
  out.push(`bind_addr = ${q(config.bindAddr)}`);
  if (config.defaultToken?.trim()) out.push(`default_token = ${q(config.defaultToken)}`);
  if (typeof config.heartbeatInterval === "number")
    out.push(`heartbeat_interval = ${config.heartbeatInterval}`);
  out.push("");

  if (config.transport && config.transport !== "tcp") {
    out.push(transportBlock(config));
    out.push("");
  } else {
    // tcp is the default; emit it explicitly for clarity.
    out.push(`[server.transport]`);
    out.push(`type = "tcp"`);
    out.push("");
  }

  for (const svc of config.services) {
    out.push(`[server.services.${serviceKey(svc.name)}]`);
    out.push(`type = ${q(svc.type)}`);
    out.push(`bind_addr = ${q(svc.bindAddr)}`);
    if (svc.token?.trim()) out.push(`token = ${q(svc.token)}`);
    if (svc.nodelay !== undefined) out.push(`nodelay = ${svc.nodelay ? "true" : "false"}`);
    out.push("");
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

/**
 * Generate a matching `client.toml`. This is a template the operator runs on the
 * machine behind NAT; `local_addr` defaults to the service's clientLocalAddr.
 */
export function generateClientToml(
  config: RatholeConfig,
  publicHost?: string,
): string {
  const remotePort = config.bindAddr.split(":").pop() ?? "2333";
  const host = publicHost?.trim() || "your-server-host";
  const out: string[] = [];
  out.push(`# rathole client config (run this on the machine behind NAT).`);
  out.push(`# Generated by rathole-manage.`);
  out.push("");
  out.push(`[client]`);
  out.push(`remote_addr = ${q(`${host}:${remotePort}`)}`);
  if (config.defaultToken?.trim()) out.push(`default_token = ${q(config.defaultToken)}`);
  out.push("");

  if (config.transport && config.transport !== "tcp") {
    out.push(`[client.transport]`);
    out.push(`type = ${q(config.transport)}`);
    if (config.transport === "noise" && config.noise?.pattern) {
      out.push(`[client.transport.noise]`);
      out.push(`pattern = ${q(config.noise.pattern)}`);
      if (config.noise.remotePublicKey)
        out.push(`remote_public_key = ${q(config.noise.remotePublicKey)}`);
    }
    if (config.transport === "websocket") {
      out.push(`[client.transport.websocket]`);
      out.push(`tls = ${config.websocket?.tls ? "true" : "false"}`);
    }
    out.push("");
  }

  for (const svc of config.services) {
    out.push(`[client.services.${serviceKey(svc.name)}]`);
    out.push(`type = ${q(svc.type)}`);
    out.push(`local_addr = ${q(svc.clientLocalAddr || localHint(svc))}`);
    if (svc.token?.trim()) out.push(`token = ${q(svc.token)}`);
    if (svc.nodelay !== undefined) out.push(`nodelay = ${svc.nodelay ? "true" : "false"}`);
    out.push("");
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function localHint(svc: RatholeService): string {
  // A sensible default local target based on the service name.
  const n = svc.name.toLowerCase();
  if (n.includes("ssh")) return "127.0.0.1:22";
  if (n.includes("web") || n.includes("http")) return "127.0.0.1:80";
  if (n.includes("rdp")) return "127.0.0.1:3389";
  return "127.0.0.1:8080";
}

/** Deterministic short hash of a string (FNV-1a) for config change detection. */
export function hashConfig(text: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

export function generateConfigs(instance: Pick<Instance, "config" | "name" | "publicHost">): GeneratedConfigs {
  const serverToml = generateServerToml(instance.config, instance.name);
  const clientToml = generateClientToml(instance.config, instance.publicHost);
  return { serverToml, clientToml, configHash: hashConfig(serverToml) };
}

export function defaultConfig(): RatholeConfig {
  return {
    bindAddr: "0.0.0.0:2333",
    defaultToken: "",
    transport: "tcp",
    services: [],
  };
}
